### ISSUE TITLE
document what the monad functions are supposed to do for each type

### ISSUE THREAD

**Issue by alltom** [NICTA/course#102]
`<$>`, `<*>`, etc have different meanings for different types. Examples are provided, but English descriptions be helpful. :)

For example, the one that tripped me up most recently was `instance Apply (State s)`. I didn't realize that the state is supposed to thread through both the arguments, so it took several attempts (that all type-checked), like:

```haskell
 (<*>) fs (State oldRunState) = State (\s ->
   let f = eval fs s
       (value, newState) = oldRunState s in
   (f value, newState))
```

Eventually I checked Tony' solution to see what I did wrong. :)

```haskell
  (<*>) (State oldFState) (State oldVState) = State (\s ->
    let (f,     newFValue) = oldFState s
        (value, newVState) = oldVState newFValue in
    (f value, newVState))
```

**Comment by tonymorris** [comment]
Fixed in d0825316a781f762700bca9b11adae2f1a2f6468
