### ISSUE TITLE
All the exercises have answers

### ISSUE THREAD

**Issue by adbrowne** [NICTA/course#108]
The current version here seems to contain the answers. All the `error "todo"` lines seem to have been replaced.

**Comment by levinotik** [comment]
:+1: I wanted to start the course tonight and found it to be rather unchallenging ;)

**Comment by tonymorris** [comment]
Sorry about that. I will fix ASAP.

**Comment by tonymorris** [comment]
Fixed in 90078d296d0e64e1c50346a343f5a26a154d1a88

Sorry.

**Comment by adbrowne** [comment]
:+1: Thanks Tony. Getting a lot out of the course.
