### ISSUE TITLE
The projects directory contains solutions

### ISSUE THREAD

**Issue by thomie** [NICTA/course#113]
Perhaps added by accident during a git merge. See also #108.

**Comment by tonymorris** [comment]
Which solutions do you see?

**Comment by thomie** [comment]
For example https://github.com/NICTA/course/blob/master/projects/TicTacToe/haskell/src/Data/TicTacToe/Interact.hs

**Comment by tonymorris** [comment]
Thanks Thomas. Can you please confirm that bf3d51a resolves it?

**Comment by thomie** [comment]
Looks ok to me. Thanks.
