### ISSUE TITLE
Potentially confusing names to new comers

### ISSUE THREAD

**Issue by chrissound** [NICTA/course#176]
http://stackoverflow.com/questions/37774347/why-is-my-implementation-of-a-map-on-a-custom-type-not-correct

I spent ages trying to figure out that error. Having functions like 'filter' just make me assume it's Haskell's Prelude functions. Even more confusing was the fact that I used **filter** in my attempt at the **map** implementation, but it (**filter**) was defined later on in the page.

**Comment by tonymorris** [comment]
The answer given in the link is incorrect. The error here is unrelated to naming. The type-error message indicates this.

**Comment by chrissound** [comment]
Correct. Correct. Correct.

My issue I'm trying to highlight is the fact that it's potentially confusing (it was to me) to have functions defined by the same name as functions commonly used in Prelude.
