### ISSUE TITLE
Progression list and course modules not compatible

### ISSUE THREAD

**Issue by xificurC** [NICTA/course#99]
I noticed a difference in the modules listed in the progression section and modules available in the course. A quick comm shows this - http://sprunge.us/fQRS . The first column shows modules recommended but not available, the second the modules not listed in the progression and the third the commons. The list could be updated to reflect the currently available modules and possibly notify if some are just libraries to help throughout the course.

**Comment by tonymorris** [comment]
Fixed in 92d8b5d14f8f32543b4f7946941caa8f4fa7f62d
